### ISSUE TITLE
ASHE Symposium

### ISSUE THREAD

**Issue by wdoyle42** [eddatasci/unrollment_proj#27]
ASHE symposium proposal, as discussed previously:

@mositelu : Institutional profiles: how individual institutions may be affected by differing approaches to the use of algorithms for predicting enrollment and graduation. 

@mpatricia01 : Overview of the unrollment project, goals and implementation steps

@btskinner : Initial results from the unrollment project--models for predicting graduation and simulations based on decisions rules. 

@ksalazar3 Karina: Discussing how misuse of predictive models can lead to spatial discrimination

@wdoyle42 : Introductions and moderation

**Comment by mositelu** [comment]
This looks great Will! I am not sure if the order you provided in the proposal is the order of panelist speaking, but if so, I would suggest to rearrange the order so that Ben is after Patricia. That way its Patricia then Ben (talking about the intro & results of the first stage of the project), and then me (broadening to a tangential analysis of institutional profiles) and then Karina (as she relates it to her work on spacial discrimination in college recruiting). Thanks for pulling this together Will!

**Comment by mpatricia01** [comment]
Looks great. I agree with @mositelu about the ordering of the panel presentation. 

I just had a minor suggestion. Maybe it would be good to include a definition of predictive algorithm at the beginning? I had no idea what this was about a few months ago so it might help the reader/reviewer get a sense of why this approach is important and relative to higher education decision making.

**Comment by btskinner** [comment]
Small change to my name pushed to the branch. 

Two items:

1. Per @mositelu's suggestion: the benefit of the current set up is that @mositelu can set a strong motivation for the unrollment project. That said, if @mpatricia01 provides that motivation in her part, @mositelu can spend more time doing what she suggests. Plus, if @ksalazar3 has a more technical presentation, then @mositelu's suggested ordering might improve the balance (_i.e._ not putting two technical discussions back to back). So I guess what I'm saying is I'm good either way, but leaning toward @mositelu's proposed change.

1. Also, agree with @mpatricia01's suggestion. I would think just a sentence or clause would do.

Otherwise, I'm good!

**Comment by ksalazar3** [comment]
Agree with @mpatricia01 suggestion about adding one sentence to define predictive analytics.

I think @mositelu's proposed ordering makes sense! And all of this seems broad enough to make changes for the actual setup if it get accepted!

All else seems good to me!

**Comment by btskinner** [comment]
Added a tag to the repo, [v0.1.0](https://github.com/eddatasci/unrollment_proj/releases/tag/v0.1.0), to represent this milestone. For more information about tags and why I think we should use them, see issue #29.
